### ISSUE TITLE
Epic: test coverage for new functions in sa_parameter_generation

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/TS1170.5-SDP#49]
Geotechnical & Functional form groups requested changes that are now  implemented as functions in this module.  (ref #47 & #48)

We have some examples for verification from Misko & Tom, so we want to add unit test coverage to show that this is implemented correctly.

Done when: 
 - [x] write test to help fix `uhs_value` function (with scipy weirdness)
 - [x] test cover using Miskos' /Chris DLTs reduced PGA tables see #47
 - [x] test cover using Tom's Sa parameter tables, see #48
